### ISSUE TITLE
@type info

### ISSUE THREAD

**Issue by bostjanl** [openEHR/specifications-ITS#15]
There are more comments on @type: DV_INTERVAL vs @type: DV_INTERVAL < DV_QUANTITY > here: https://openehr.atlassian.net/wiki/display/spec/AQL+Result+Set+work+area.
Should we drop this extra information and only specify: @type: DV_INTERVAL?

**Comment by sebastian-iancu** [comment]
I agree.
If understand correctly, an example could be:
```javascript
{
	"@type": "DV_INTERVAL",
	"lower": {
		"@type": "DV_DATE_TIME",
		"value": "20160624T124126,000+0200"
	},
	"upper": {
		"@type": "DV_DATE_TIME",
		"value": "20160625T124340,000+0200"
	},
	"lower_included": true,
	"upper_included": true,
	"lower_unbounded": false,
	"upper_unbounded": false
}
```

**Comment by ErikSundvall** [comment]
I believe dropping the `<extra_info>` is ok as clarified by @pieterbos nice example in the discussion in the above mentioned wiki-thread:

```
Example of a JSON DV_REAL: { @type: "DV_REAL", magnitude: 0.0, units: "kg"}
Example of a JSON DV_QUANTITY: { @type: "DV_QUANTITY", magnitude: 1}
```
Everything needed for deserializers (or GUI-rendering code) is likely already there in the `@type:` of the data in child instances.

**Comment by bostjanl** [comment]
Decided on simple approach
