### ISSUE TITLE
PUT /ehr/{ehrId}/ehr_status status 412 implications / questions

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS#35]
Current:

1.
`The existing `versionUid` of `EHR_STATUS` resource must be specified in the `Match-If` header.`
Ref https://github.com/openEHR/specifications-ITS/blob/master/apiary.apib#L436

2.
```
+ Response 412
    `412 Conflict` is return when `Match-If` header doesn't match the latest trunk version. 
    Returns latest trunk version in the `Content-Location` and `ETag` headers.
```
https://github.com/openEHR/specifications-ITS/blob/master/apiary.apib#L548-L551

Does 2. implies that versionUid described in 1. should be the current trunk version? Or can versionUid be the UID of any version of the EHR_STATUS?

If it can be only the trunk version, is the versionUid needed? I think knowing the ehrUid and that the status is the trunk, that identifies just one version of the status.

**Comment by bostjanl** [comment]
Better explained in the split version, please open a new issue if still unclear.

**Comment by ppazos** [comment]
@bostjanl not seeing any difference on the split version on master, missing PR merge?

ref https://github.com/openEHR/specifications-ITS/blob/master/REST_API/includes/ehr_status.apib#L232-L235

**Comment by bostjanl** [comment]
I have added 'latest' before 'existing', the idea is that it has to be the latest version otherwise there's no point in having this header. Is it clear enough? If you have a better wording for it, please let me know.
