### ISSUE TITLE
Some endpoints still use singular resources

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS#37]
```
GET /ehr/{ehrId}/versioned_ehr_access/version{?versionSelector}
POST /ehr/{ehrId}/versioned_ehr_access/version
POST /ehr/{ehrId}/versioned_compositions/{uid}/version{?format}
GET /ehr/{ehrId}/versioned_compositions/{uid}/version/{versionUid}{?format}
GET /ehr/{ehrId}/versioned_compositions/{uid}/version{?versionSelector,format}
GET /ehr/{ehrId}/versioned_ehr_status/version?{versionSelector}
GET /ehr/{ehrId}/versioned_ehr_status/version/{versionUid}
```

"version" should be "versions".

From https://github.com/openEHR/specifications-ITS/blob/master/apiary.apib

**Comment by bostjanl** [comment]
This is the old file - apiary.apib, which has been split into several pieces to make it more manageable. Please see contents of folder REST_API for the current set of files. These can also be viewed rendered here: https://openehr.github.io/specifications-ITS/

**Comment by ppazos** [comment]
@bostjanl the issue is still valid since the same URLs appear on the separated files, like:

https://github.com/openEHR/specifications-ITS/blob/master/REST_API/includes/ehr_status.apib#L310

https://github.com/openEHR/specifications-ITS/blob/master/REST_API/includes/ehr_status.apib#L402


BTW, that old file can be removed?
