### ISSUE TITLE
Define XML Schema for the EHR resource

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS#4]
The openEHR XSD doesn't include EHR and it's related objects and we need a schema to represent those resources on the REST API.

This should include EHR_STATUS and EHR_ACCESS.

We also need to define how to represent a collection or list of EHRs in XML. The same representation can be used for other collections, like endpoints that return collections of compositions or contributions.

**Comment by ErikSundvall** [comment]
In the directory https://github.com/LiU-IMT/EEE/tree/master/src/main/xsd you can find the (not so well tested) XML-schemas from LiU EEE. Feel free to reuse, modify and comoment. Highlights:

- EHR: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/EEE-flat-storage-v1.xsd
- CONTRIBUTION, EHR_STATUS, EHR_ACCESS, VERSIONED_OBJECTs etc: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/EEE-v1.xsd (note that the CotributionBuild class in that file will likely not be part of the current API we are specifying now, maybe rather in a later separate optional spec)
- XML-based query result: https://github.com/LiU-IMT/EEE/blob/master/src/main/xsd/xml-result-v1.xsd

**Comment by ErikSundvall** [comment]
Suggesting that we close this issue and continue in the related issue #11
