### ISSUE TITLE
Meaning of qualified query name in /query calls?

### ISSUE THREAD

**Issue by wolandscat** [openEHR/specifications-ITS#55]
It's not clear to me what the reverse domain name qualifier in the qualified query name pertains to. Whose domain is it? It would seem simpler to either have a flat id space, or else some kind of ids based on a pathing concept that allows queries to be classified in a tree-space.

**Comment by bostjanl** [comment]
Everybody is happy with current style.

**Comment by bostjanl** [comment]
We need to add more description about this.
