### ISSUE TITLE
Clarify RM types for returned data when creating an EHR 

### ISSUE THREAD

**Issue by serefarikan** [openEHR/specifications-ITS#64]
The [POST request for creating a new EHR](https://www.openehr.org/releases/ITS/latest/docs/ehr.html#ehr-ehr-post) is documented to return a data structure that consists of objects and string fields. However, it is not clear what these objects should look like in terms of RM types. 

Please specify expected structures in regards to RM.

**Comment by bjornna** [comment]
Will the following changes be sufficient? 

1. Define that the returned object is of class:[EHR](https://www.openehr.org/releases/RM/latest/docs/ehr/ehr.html#_ehr_class) 


2. Change the (json) definition of the EHR_STATUS to match the reference mode: 
`1..1 | ehr_status: OBJECT_REF | Reference to EHR_STATUS object for this EHR.`
