### ISSUE TITLE
Remove reference to deleted EHRs from description of Get EHR_STATUS version by time

### ISSUE THREAD

**Issue by serefarikan** [openEHR/specifications-ITS#65]
Since openEHR spec does not describe the semantics of a deleted EHR and it is not currently clear how this could be expressed in the REST api, the reference to deleted ehr in the following text would better be removed:

> 404 Not Found returned when EHR with ehr_id does not exist or has been deleted or a version of an EHR_STATUS resource does not exist at the specified version_at_time.

This is necessary since this statement refers to functionality that is not defined in the current rest specs and therefore cannot be used to write tests for the get ehr status semantics above.

**Comment by bostjanl** [comment]
The part mentioning deleted EHR has been removed.
