### ISSUE TITLE
{preceding_version_uid} as path or header parameter?

### ISSUE THREAD

**Issue by jakesmolka** [openEHR/specifications-ITS#73]
Updating resources COMPOSITION and DIRECTORY are somewhat similar methods (in scope of this question), but providing `{preceding_version_uid}` is handled differently in each case. 

- PUT `/ehr/{ehr_id}/composition/{preceding_version_uid}` contains the uid as path parameter
- PUT `/ehr/{ehr_id}/directory` contains the uid as `If-Match` header parameter, which is said to be mandatory

Same is true for deletion too.

Why do these cases need different implementations of providing `{preceding_version_uid}`?

**Comment by jakesmolka** [comment]
Sorry, just found the reason: https://openehr.github.io/specifications-ITS/ehr.html#design-considerations-http-headers

But to understand it completely, I really would like to know why "This is only required by a small set of resources"? I could image that `directory` objects are way more likely to be target of multiple requests at the same time than a specific `composition`. That's not really a technical explanation though.

**Comment by bostjanl** [comment]
We will change the composition PUT to use versioned_object_uid as path parameter and If-Match header for preceding version_uid.
